laplsolv:laplsolv_par.f90
	ifort -fopenmp $^ -o $@

laplsolv_s:laplsolv.f90
	ifort -fopenmp $^ -o $@

laplsolv_home:laplsolv_par.f90
	gfortran -fopenmp $^ -o $@ 

laplsolv_s_home:laplsolv.f90
	gfortran -fopenmp $^ -o $@ 

